// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdpIA6cozQLPT-pTGuVWAblJzPv1L9fA0',
    appId: '1:260601859262:web:88c36f75e44d2cdface2ef',
    messagingSenderId: '260601859262',
    projectId: 'live-tv-810ba',
    authDomain: 'live-tv-810ba.firebaseapp.com',
    storageBucket: 'live-tv-810ba.firebasestorage.app',
    measurementId: 'G-16Y5B6FH2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz_WkRHAGFuBrXoYq6du7oA5Gbb2klDBo',
    appId: '1:260601859262:android:3617760b0fb84186ace2ef',
    messagingSenderId: '260601859262',
    projectId: 'live-tv-810ba',
    storageBucket: 'live-tv-810ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD5ovW3lLTC7N2OfIZdGk1wc7wlodCGf4',
    appId: '1:260601859262:ios:8076906fbafcdfc0ace2ef',
    messagingSenderId: '260601859262',
    projectId: 'live-tv-810ba',
    storageBucket: 'live-tv-810ba.firebasestorage.app',
    iosBundleId: 'com.livetv.livetvApp',
  );
}
