# Generated by Django 6.0.6 on 2026-06-09 12:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('regions', models.JSONField(default=list)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('deactivated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('region', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(blank=True, db_index=True, max_length=128)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('stream_url', models.URLField(max_length=1000)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_date', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['region', 'category', 'name'],
                'indexes': [models.Index(fields=['region', 'is_active'], name='catalog_cat_region_39dd86_idx'), models.Index(fields=['region', 'category'], name='catalog_cat_region_62ace3_idx')],
            },
        ),
    ]
