# Generated by Django 6.0.6 on 2026-06-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogchannel',
            options={'ordering': ['region', 'category', 'name'], 'verbose_name': 'TV channel', 'verbose_name_plural': 'TV channels'},
        ),
        migrations.AddField(
            model_name='catalogsyncrun',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, help_text='Upstream channels skipped because stream URL did not respond.'),
        ),
    ]
