# Generated by Django 6.0.6 on 2026-06-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalogchannel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogchannel',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
