# Generated by Django 6.0.6 on 2026-06-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalogchannel_failure_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactiveCatalogChannel',
            fields=[
            ],
            options={
                'verbose_name': 'inactive TV channel (review)',
                'verbose_name_plural': 'inactive TV channels (review)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.catalogchannel',),
        ),
        migrations.AddField(
            model_name='catalogchannel',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogchannel',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('user_reports', 'User playback failures'), ('sync_missing', 'Missing from catalog sync'), ('health_check', 'Server health check'), ('admin', 'Manual (admin)')], db_index=True, max_length=32),
        ),
    ]
