# Generated by Django 6.0.6 on 2026-06-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_inactivecatalogchannel_catalogchannel_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogchannel',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('user_reports', 'User playback failures'), ('sync_missing', 'Missing from catalog sync'), ('health_check', 'Server health check'), ('dead_link', 'Dead stream URL (admin)'), ('admin', 'Manual (admin)')], db_index=True, max_length=32),
        ),
    ]
