# Generated by Django 6.0.6 on 2026-06-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_group_key_name_only'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='catalogchannel',
            new_name='catalog_cat_group_k_1a51d0_idx',
            old_name='catalog_cat_group_k_0f0f0d_idx',
        ),
        migrations.AddField(
            model_name='catalogchannel',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='catalogchannel',
            index=models.Index(fields=['is_active', '-view_count'], name='catalog_cat_is_acti_8550e7_idx'),
        ),
    ]
