# Generated by Django 6.0.6 on 2026-06-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_widen_catalogchannel_text_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogchannel',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('user_reports', 'User playback failures'), ('sync_missing', 'Missing from catalog sync'), ('health_check', 'Server health check'), ('dead_link', 'Dead stream URL (admin)'), ('unsupported_format', 'Unsupported stream format (non-HLS)'), ('admin', 'Manual (admin)')], db_index=True, max_length=32),
        ),
    ]
