# Generated by Django 6.0.6 on 2026-06-09 11:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sport', models.CharField(db_index=True, max_length=64)),
                ('home_team', models.CharField(max_length=128)),
                ('away_team', models.CharField(max_length=128)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], db_index=True, default='scheduled', max_length=16)),
                ('poster_url', models.URLField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sort_order', 'starts_at'],
                'indexes': [models.Index(fields=['status', 'starts_at'], name='matches_mat_status_1cc512_idx')],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('logo_url', models.URLField(blank=True)),
                ('stream_url', models.URLField()),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('url_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='matches.match')),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['match', 'priority'], name='matches_cha_match_i_130f63_idx')],
            },
        ),
    ]
