# Generated by Django 6.0.6 on 2026-06-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('matches', '0003_channel_failure_count'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_mat_starts__8178bb_idx',
            old_name='matches_mat_starts__a1b2c3_idx',
        ),
        migrations.AddField(
            model_name='channel',
            name='catalog_channel',
            field=models.ForeignKey(blank=True, help_text='Optional link to synced catalog; stream URL updates propagate on sync.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_channels', to='catalog.catalogchannel'),
        ),
    ]
