# Generated by Django 6.0.6 on 2026-06-09 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('matches', '0004_rename_matches_mat_starts__a1b2c3_idx_matches_mat_starts__8178bb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='follow_catalog_stream',
            field=models.BooleanField(default=False, editable=False, help_text="When true, catalog sync updates this channel's stream URL automatically."),
        ),
        migrations.AlterField(
            model_name='channel',
            name='catalog_channel',
            field=models.ForeignKey(blank=True, help_text='Optional — pick from synced catalog or leave empty for a manual stream.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_channels', to='catalog.catalogchannel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='channel',
            name='stream_url',
            field=models.URLField(blank=True, help_text='HLS/m3u8 URL. Filled from catalog when selected, or enter your own.'),
        ),
    ]
