# Generated by Django 6.0.6 on 2026-06-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_channel_follow_catalog_stream_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactiveMatchChannel',
            fields=[
            ],
            options={
                'verbose_name': 'inactive match channel (review)',
                'verbose_name_plural': 'inactive match channels (review)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matches.channel',),
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'match channel', 'verbose_name_plural': 'match channels'},
        ),
        migrations.AddField(
            model_name='channel',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('user_reports', 'User playback failures'), ('sync_missing', 'Missing from catalog sync'), ('health_check', 'Server health check'), ('admin', 'Manual (admin)')], db_index=True, max_length=32),
        ),
    ]
