# Generated by Django 6.0.6 on 2026-06-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_dead_link_deactivation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_group',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='channel',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('user_reports', 'User playback failures'), ('sync_missing', 'Missing from catalog sync'), ('health_check', 'Server health check'), ('dead_link', 'Dead stream URL (admin)'), ('unsupported_format', 'Unsupported stream format (non-HLS)'), ('admin', 'Manual (admin)')], db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('match_number__isnull', False)), fields=('sport', 'match_number'), name='matches_unique_sport_match_number'),
        ),
    ]
