# Generated by Django 6.0.6 on 2026-06-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprelease',
            name='apk_file',
            field=models.FileField(blank=True, help_text='Uploaded APK; download URL is filled automatically on save.', upload_to='releases/'),
        ),
        migrations.AlterField(
            model_name='apprelease',
            name='download_url',
            field=models.URLField(blank=True, help_text='Public HTTPS link served to the app (auto-set when APK file is uploaded).', max_length=2048),
        ),
    ]
