# Generated by Django 6.0.6 on 2026-06-15 05:32

import releases.apk_files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_apprelease_apk_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprelease',
            name='apk_file',
            field=models.FileField(blank=True, help_text='Uploaded APK; download URL is filled automatically on save.', upload_to=releases.apk_files.release_apk_upload_to),
        ),
    ]
